version: "2.2"

volumes:
  postgres:
  redis:

services:
  sidekiq:
    build: .
    command: bundle exec sidekiq -r ./lib/stocksdb/sidekiq.rb
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:9.6.6-alpine
    ports:
      - 5239:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:4.0.2-alpine
    command:
      - redis-server
      - --appendonly
      - "yes"
    volumes:
      - redis:/data
